In [1]:
import torch
import numpy as np
import os

In [2]:
x=torch.arange(start=1,end=10,step=4)
y=torch.arange(start=5,end=15,step=4)

In [3]:
A=torch.rand((3,3))
A

tensor([[0.5697, 0.2626, 0.6464],
        [0.4445, 0.0119, 0.7035],
        [0.2831, 0.2052, 0.3429]])

In [4]:
A[0,0]=12
A

tensor([[1.2000e+01, 2.6256e-01, 6.4641e-01],
        [4.4445e-01, 1.1922e-02, 7.0347e-01],
        [2.8306e-01, 2.0524e-01, 3.4287e-01]])

In [5]:
x.shape,y.shape

(torch.Size([3]), torch.Size([3]))

In [6]:
x+y

tensor([ 6, 14, 22])

In [7]:
A=torch.rand(size=(3,3))
A

tensor([[0.1559, 0.2944, 0.4970],
        [0.7016, 0.4627, 0.4603],
        [0.7778, 0.9172, 0.7999]])

In [8]:
A.matrix_exp()

tensor([[1.7405, 0.8951, 1.0973],
        [1.4869, 2.2834, 1.3395],
        [2.0997, 2.2557, 3.1977]])

In [9]:
a=torch.rand((3,5))

In [10]:
a

tensor([[0.7490, 0.0957, 0.0493, 0.6459, 0.3282],
        [0.7088, 0.4812, 0.5164, 0.9787, 0.0287],
        [0.2114, 0.4932, 0.3663, 0.7667, 0.2950]])

In [11]:
b=torch.zeros((1,5))

In [12]:
b

tensor([[0., 0., 0., 0., 0.]])

In [13]:
a-b

tensor([[0.7490, 0.0957, 0.0493, 0.6459, 0.3282],
        [0.7088, 0.4812, 0.5164, 0.9787, 0.0287],
        [0.2114, 0.4932, 0.3663, 0.7667, 0.2950]])

In [14]:
0.8414-1

-0.15859999999999996

In [15]:
x=torch.tensor(5.0,requires_grad=True)
y=torch.tensor(5.0,requires_grad=True)

In [16]:
f=x**2+y**2

In [18]:
f.backward()

In [20]:
f.grad_fn

In [21]:
x.grad

tensor(10.)

In [22]:
y.grad

tensor(10.)

In [23]:
f2=x**2*y**2

In [24]:
f2.backward()

In [25]:
f2.grad_fn

In [26]:
x.grad

tensor(260.)

In [27]:
x

tensor(5., requires_grad=True)

In [28]:
y.grad

tensor(260.)

In [29]:
f3 = x**2 + 1

In [36]:
f7.backward()

In [37]:
x.grad

tensor(355.)

In [35]:
f7 = x**3 + 1

In [38]:
3*5

15

In [40]:
3*25

75

In [41]:
280+75

355

In [55]:
from torch.autograd import grad

def nth_derivative(f, wrt, n=2):
    
    for i in range(n):
        grads = grad(f, wrt, create_graph=True)
        print("g",grads)
        grads=grads[0]

        
    return grads

In [56]:
f = x**2 + x**3

# double derivative
nth_derivative(f, x)

g (tensor(85., grad_fn=<AddBackward0>),)
g (tensor(85., grad_fn=<AddBackward0>),)


tensor(85., grad_fn=<AddBackward0>)

In [48]:
3*25

75